services:
  postgres:
    image: postgres:16
    container_name: hackaton-postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

      #  backend:
      #command: uvicorn backend.app:app --host 0.0.0.0 --port 4000
      #build:
      #context: .
      #env_file:
      # - .env
      # depends_on:
      #- postgres
      #    ports:
      #  - "4000:4000"
      # healthcheck:
      # test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      #interval: 10s
      #timeout: 10s
      
      # retries: 5
  
